---
title: "Practica PCA"
author: "Eduardo Martínez Tena"
format:
  html:
    theme: [default, style.scss]
    toc: true
    toc-location: left
    toc-title: indice
    toc-depth: 5
    fig-cap-location: margin
editor: visual
---

Aquí os dejo todas librerías necesarias:

```{r}
#| message: false
#| warning: false
rm(list = ls())
# Manejo de datos
library(tidyverse)
# Importar Excel
library(readxl)
# Recopilarción de temas, escalas y utilidades adicionales de ggplot2
library(hrbrthemes)
# Mostrar tablas en HTML (datatable)
library(DT)
# Combinar gráficos
library(gridExtra)
# PCA
library(FactoMineR)
library(factoextra)
# Correlacion
library(corrplot)
# Modelos
library(tidymodels)
# Para grafico de Correlacion CP vs X
library(hrbrthemes)
library(GGally)
library(viridis)
```

El conjunto de datos `euro_contam` está compuesto por 14 variables de carácter socio económico y relacionadas con las emisiones de CO2 para 27 países de la Unión Europea (observaciones).

Para reducir el número de variables e intentar encontrar relaciones, tanto entre variables como entre países, realizar los siguientes apartados.

-   Realizar un análisis de componentes principales sobre la matriz de correlaciones.

    -   Obtén los autovalores y autovectores
    -   ¿Con cuantas componentes nos quedaríamos? (al menos un 75% de la varianza total explicada)

-   Hacer de nuevo el análisis, pero ahora indicando el número de componentes principales que hemos decidido retener. Sobre este análisis contestar los siguientes apartados.

    -   ¿Cómo se calculan las Componentes (expresa las ecuaciones)?
    -   ¿Con que variables está más correlada la segunda componente?
    -   ¿Qué más puedes decir sobre las componentes y variables originales? ¿alguna relación?
